
/*PRASIT KRONGMARERNG 6419410031*/

CREATE TABLE CUSTOMER(
	Customer_ID			CHAR(5) NOT NULL,
	Customer_Name		VARCHAR(25) CONSTRAINT Name_Check CHECK (Customer_Name > 1),
	Customer_Address	VARCHAR(100),
	PRIMARY KEY(Customer_ID)
)

CREATE  TABLE  ORDERS(
	Order_ID	CHAR(5)		NOT NULL,
	Order_Date	DATETIME	NOT NULL,
	Customer_ID CHAR(5)		NOT NULL,
	PRIMARY KEY(Order_ID),
	FOREIGN KEY(Customer_ID) REFERENCES CUSTOMER(Customer_ID)
    ON  DELETE  NO ACTION
    ON  UPDATE CASCADE
)

CREATE INDEX nameIndex ON CUSTOMER(CUSTOMER_Name);